// Initialize arrays and variables to hold sequence data and level count
var sequenceMade = [];  // Stores the sequence generated by the game
var sequenceUser = [];  // Stores the sequence clicked by the user
var audio = [  // Array holding audio files for each color and the error sound
    new Audio("./sounds/green.mp3"),
    new Audio("./sounds/blue.mp3"),
    new Audio("./sounds/red.mp3"),
    new Audio("./sounds/yellow.mp3"),
    new Audio("./sounds/wrong.mp3")
];
var levelCounter = 0;  // Tracks the current level of the game
var level = 0;  // Unused variable, can be removed

// Event listener for the "Enter" key to start the game
$(document).on("keydown", function (e) {
    if (e.keyCode === 13) {
        nextSequence();  // Calls nextSequence() to start the game
    }
});

// Function to generate a random number (0-3) and push it to sequenceMade array
function nextSequence() {
    var randomNumber = Math.floor(Math.random() * 4);  // Generate a random number between 0 and 3
    sequenceMade.push(randomNumber);  // Add the random number to the sequence
    showSequence(sequenceMade[sequenceMade.length - 1]);  // Show the latest color in the sequence
    changeLevel();  // Increase the level and update the display
    sequenceUser = [];  // Reset the user's sequence
};

// Function to display the color and play sound for each option
function showSequence(element) {
    switch (element) {
        case 0:
            audio[0].play();  // Play green sound
            $("#green").addClass("dissapear");  // Add disappearing effect to green button
            setTimeout(function () {
                $("#green").removeClass("dissapear");  // Remove disappearing effect after 250ms
            }, 250);
            break;
        case 1:
            audio[2].play();  // Play red sound
            $("#red").addClass("dissapear");
            setTimeout(function () {
                $("#red").removeClass("dissapear");
            }, 250);
            break;
        case 2:
            audio[3].play();  // Play yellow sound
            $("#yellow").addClass("dissapear");
            setTimeout(function () {
                $("#yellow").removeClass("dissapear");
            }, 250);
            break;
        case 3:
            audio[1].play();  // Play blue sound
            $("#blue").addClass("dissapear");
            setTimeout(function () {
                $("#blue").removeClass("dissapear");
            }, 250);
            break;
    }
}

// Function to increment the level counter and update the level display
function changeLevel() {
    levelCounter++;  // Increment level counter
    $("#level-title").text(`Level: ${levelCounter}`);  // Update the level text on the screen
};

// Event listener for button clicks
$(".btn").click(function (e) {
    var userClicked = $(this).attr("id");  // Get the ID of the clicked button
    switch (userClicked) {
        case "green":
            sequenceUser.push(0);  // Add green to the user's sequence
            showSequence(0);  // Show the green color with sound
            break;
        case "red":
            sequenceUser.push(1);  // Add red to the user's sequence
            showSequence(1);  // Show the red color with sound
            break;
        case "yellow":
            sequenceUser.push(2);  // Add yellow to the user's sequence
            showSequence(2);  // Show the yellow color with sound
            break;
        case "blue":
            sequenceUser.push(3);  // Add blue to the user's sequence
            showSequence(3);  // Show the blue color with sound
            break;
    }
    checkSequence(sequenceUser.length - 1);  // Check if the user's sequence is correct so far
});

// Function to check if the user's sequence matches the generated sequence
function checkSequence(indexOfArray) {
    if (sequenceUser[indexOfArray] === sequenceMade[indexOfArray]) {
        // If the current button clicked matches the sequence, check if the entire sequence is complete
        if (sequenceMade.length === sequenceUser.length) {
            setTimeout(function () {
                nextSequence();  // If complete, move to the next sequence
            }, 1000);
        }
    } else {
        launchError();  // If there's an error, trigger the error sequence
    }
}

// Function to handle errors when the user clicks the wrong sequence
function launchError() {
    $("body").css("background-color", "red");  // Change the background color to red
    $("h1").text("Game Over");  // Display "Game Over"
    setTimeout(function () {
        $("h1").text("Press Enter Key to start");  // Reset the title after 1.5 seconds
        $("body").css("background-color", "#011F3F");  // Reset the background color to navy
    }, 1500);
    audio[4].play();  // Play the "wrong" sound
    levelCounter = 0;  // Reset the level counter
    sequenceMade = [];  // Clear the sequenceMade array to start a new game
}
